---
title: "@realDonaldTrump Tweets for Dow Jones Index Direction Prediction"
author: Dmitry Petukhov
output: github_document
---

_Train ML-model that predict Dow Jones Index direction by @realDonaldTrump tweets._


Import dependencies and read config:
```{r set_env_options}
options(max.print = 1e3, scipen = 999, width = 1e2)
options(stringsAsFactors = F)
```

```{r import_dependencies, echo=TRUE}
suppressPackageStartupMessages({
  library(h2o)
  
  library(dplyr)
  library(tidyr)
  library(purrr)
  library(magrittr)
  
  library(lubridate)
})

```

```{r read_secrets, echo=TRUE}
secrets <- config::get(file = "secrets.yml")
```


## Load dataset
```{r load_dataset}
tweets <- readRDS("cache/2019-09-06.rds") #! set your cache here

min(tweets$created_date)
max(tweets$created_date)

tweets %>% count(direction)

```


## Init H2O cluster
```{r h2o_init}
h2o.init(nthreads = -1, # use all cores
         max_mem_size = "64G") # max mem size
```

## Prepare dataset

Set metadata:
```{r set_metadata}
label <- "direction"
features <- setdiff(names(tweets), c("created_date", "text_total", label))
```

Split dataset:
```{r split_dataset}
tweets %<>% 
  mutate(direction = as.factor(direction)) 

train_dt <- tweets %>% 
  filter(created_date < Sys.Date() - months(9)) %>%
  as.h2o

dim(train_dt)

valid_dt <- tweets %>% 
  filter(created_date >= Sys.Date() - months(9) & created_date < Sys.Date() - months(3)) %>% 
  as.h2o

dim(valid_dt)

test_dt <- tweets %>% 
  filter(created_date >= Sys.Date() - months(3)) %>% 
  as.h2o()

dim(test_dt)

```


## Train Model
Start AutoML models training:
```{r h2o_automl}
auto <- h2o.automl(x = features, y = label,
                   training_frame = train_dt,
                   validation_frame = valid_dt,
                   leaderboard_frame = test_dt,
                   max_runtime_secs = 60*1, #! set appropriate duration of searching model
                   seed = 314)
```


View leaderboard:
```{r leaderboard}
lb <- auto@leaderboard
lb
```


View best model:
```{r best_model}
best <- auto@leader
best
```


View feature importance:
```{r varimp_plot}
h2o.varimp_plot(best, num_of_features = 10)
```


